export const MEDIA_KIT_ROW_GRABBER_SIZE_PX = 32;
export const MEDIA_KIT_ROW_GRABBER_GAP_PX = 8;
export const MEDIA_KIT_ROW_MENU_SIZE_PX = 32;
export const MEDIA_KIT_ROW_MENU_GAP_PX = 8;

export const MEDIA_KIT_ROW_LEFT_GUTTER_PX =
  MEDIA_KIT_ROW_GRABBER_SIZE_PX + MEDIA_KIT_ROW_GRABBER_GAP_PX;

export const MEDIA_KIT_ROW_RIGHT_GUTTER_PX =
  MEDIA_KIT_ROW_MENU_SIZE_PX + MEDIA_KIT_ROW_MENU_GAP_PX;
